### ISSUE TITLE
Buffersize in configHelpers

### ISSUE THREAD

**Issue by ulegan** [pinae/PM2.5-CO2-Watcher#2]
Hi Pina,
I think the buffer for deviceName in **configHelpers.h** is too small:
`char deviceName[23] = {'A', 'E', 'V', 'O', 'C', '-', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};`
It should be:
`char deviceName[25] = {'A', 'E', 'V', 'O', 'C', '-', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};`
becaus in **configHelpers.cpp** the zero's are overwritten with an 18-character long string, 
but there is only space for 17, and no space for a trailing \0:
`DeviceName::DeviceName() {
    byte mac[6]; WiFi.macAddress(mac);
    char macStr[18];
    sprintf(&macStr[0], "%x:%x:%x:%x:%x:%x", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    strncpy(&deviceName[6], macStr, 18);
}`

Second issue here. Shouldn't it be:
`    sprintf(&macStr[0], "%02x:%02x:%02x:%02x:%02x:%02x", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);`
so the string will always have 18 characters, independent from the mac?

Uwe

**Comment by pinae** [comment]
`macStr` always has 18 characters because of the trailing `'\0'`. I exteded `deviceName` by one byte because there was no room for the  `'\0'`. That adds up to 24 because there is no 0 between the dash and the charactes of the `macStr`.

Thanks for opening the issue!
