### ISSUE TITLE
mqtt.cpp createFullTopicStr()

### ISSUE THREAD

**Issue by WSchimi** [pinae/PM2.5-CO2-Watcher#6]
Hi Pina,

mqtt.cpp line 78: *(fullTopicStr + topicLen+1) = 0; // <-- the 0 is OUT OF ALLOCATED MEMORY!
see allocation at line 74: char* fullTopicStr = (char*) calloc(topicLen+1, sizeof(char));

proposal for line 78: fullTopicStr[topicLen] = '\0';

Best regards
Walter

**Comment by pinae** [comment]
I accepted your suggestion. Thank You for the help!

**Comment by WSchimi** [comment]
> Hi Pina,
> 
> mqtt.cpp line 78: _(fullTopicStr + topicLen+1) = 0; // <-- the 0 is OUT OF ALLOCATED MEMORY! see allocation at line 74: char_ fullTopicStr = (char*) calloc(topicLen+1, sizeof(char));
> 
> proposal for line 78: fullTopicStr[topicLen] = '\0';
> 
> Best regards Walter

Hi Pina,
the **ERROR IS NOT FIXED!** 
The code "(fullTopicStr + topicLen+1) = " writes 1 Byte behind the allocated memory!
Allocation code: "char* fullTopicStr = (char*) calloc(topicLen+1, sizeof(char));"
The management data of the pool or other important data may already be stored there.

Example: topicLen = 20:
-> 21 Bytes are allocated (from Byte *(fullTopicStr+0) till *(fullTopicStr+20) or *(fullTopicStr + topicLen))
-> "(fullTopicStr + topicLen+1) = '\0' writes at **Byte 21** behind memory at pointer *fullTopicStr
-> my proposal for line 78: **fullTopicStr[topicLen] = '\0';** or ***(fullTopicStr + topicLen) = '\0';**

Best regards Walter
